### ISSUE TITLE
Incorrect comment in README.md

### ISSUE THREAD

**Issue by aravind-craft** [hamxiaoz/open-folder-with-vs-code#2]
README says - its a commented line - 

-- open in Sublime Text

it should actually say

-- open in Visual Studio Code

so as to not confuse the reader. There is a different github page for Sublime Text finder icon, where it correctly says 'open in Sublime Text'

**Comment by websocket98765** [comment]
I also wonder if `subl()` is an Apple Script function name or if that naming is a remnant from Sublime Text's `subl` CLI tool, and could be changed to `code` for Visual Studio Code?

**Comment by hamxiaoz** [comment]
update, thanks @aravind-murthy
