### ISSUE TITLE
"The application “Open in VS Code” can’t be opened." error after right clicking the app

### ISSUE THREAD

**Issue by moguzozcan** [hamxiaoz/open-folder-with-vs-code#6]
Hi, 

I am stucked at the "Right-click to open to pass the Mac security check" step, it does not work and it gives the following error, any idea?

![image](https://user-images.githubusercontent.com/8096278/75094249-57c6a600-5581-11ea-8d35-46dce5750eef.png)

**Comment by PorriD63** [comment]
<img width="983" alt="截圖 2020-05-12 上午11 33 45" src="https://user-images.githubusercontent.com/17632773/81635798-c27ed380-9444-11ea-83db-2b92295181a9.png">

**Comment by ksmarty** [comment]
For the lazy:

```
cd Downloads/Open\ in\ VS\ Code.app/Contents/MacOS/
chmod +x droplet
```

**Comment by hamxiaoz** [comment]
Thanks guys, updated the readme

**Comment by natuan62** [comment]
> cd Downloads/Open\ in\ VS\ Code.app/Contents/MacOS/

I got error

![image](https://user-images.githubusercontent.com/10808157/150052610-0114e644-d4ac-4583-8244-3accd7c7cebd.png)

cd: no such file or directory: Downloads/Open in VS Code.app/Contents/MacOS/

**Comment by PorriD63** [comment]
Forgive my poor English.

1. Move the 'Open in VS Code' to Application folder.
![CleanShot 2022-01-19 at 19 05 58@2x](https://user-images.githubusercontent.com/17632773/150118215-76dc4aa9-8958-4a13-97ca-2ae37d5f6082.png)

2.

```
cd /Applications/Open\ in\ VS\ Code.app/Contents/MacOS/
chmod +x droplet
```
![CleanShot 2022-01-19 at 18 54 57@2x](https://user-images.githubusercontent.com/17632773/150116793-dd9c1f69-72f5-42ec-a612-f56d84b110e9.png)

**Comment by natuan62** [comment]
It worked, thanks!
